services:
  - type: static
    name: buywise-frontend
    buildCommand: npm run build
    staticPublishPath: ./build
    routes:
      - path: "/*"
        methods:
          - GET
        status: 200
        dest: /index.html
